### ISSUE TITLE
StackTrace

### ISSUE THREAD

**Issue by madoar** [Rails-18xx/Rails#200]
I just found the following stack trace in my terminal. Please take it with a bit of salt because I'm currently using a build based on #184

```
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.remove(ArrayList.java:535)
	at net.sf.rails.game.state.ArrayListState.change(ArrayListState.java:192)
	at net.sf.rails.game.state.ArrayListChange.undo(ArrayListChange.java:39)
	at net.sf.rails.game.state.ChangeSet.unexecute(ChangeSet.java:71)
	at net.sf.rails.game.state.ChangeStack.executeUndo(ChangeStack.java:156)
	at net.sf.rails.game.state.ChangeStack.undo(ChangeStack.java:126)
	at net.sf.rails.game.GameManager.processGameActions(GameManager.java:829)
	at net.sf.rails.game.GameManager.process(GameManager.java:723)
	at net.sf.rails.ui.swing.GameUIManager.processOnServer(GameUIManager.java:482)
	at net.sf.rails.ui.swing.GameUIManager.processAction(GameUIManager.java:408)
	at net.sf.rails.ui.swing.StatusWindow.process(StatusWindow.java:741)
	at net.sf.rails.ui.swing.StatusWindow.actionPerformed(StatusWindow.java:726)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6631)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6396)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5007)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4839)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4839)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by jklap** [comment]
Can it be reproduced with a saved game file? If so, can you provide it?

**Comment by madoar** [comment]
No I don't have a save game for this error. I only saw it when I was closing IntelliJ :/

**Comment by jklap** [comment]
I'll eyeball the code but suspect this will be hard to track down. Just looking at the stack trace it looks like either you were undo'ing an action or there was an undo in the game file (are they even stored??) and in removing the action it choked as it attempted to remove the action from the change set array when it didn't exist. Maybe an undo was being applied where there wasn't an action to actually undo? The guys I'm playing with have run into all sorts of issues with undo (caveat many may be related to polling and continually reloads of the game...)
