### ISSUE TITLE
Rails freezes when adding the same player name during game creation

### ISSUE THREAD

**Issue by madoar** [Rails-18xx/Rails#55]
When you add the same player name two times during the game creation and start a new game afterwards, the game will freeze with 0% process in the progress bar.

**Comment by jklap** [comment]
```
Exception in thread "Thread-0" java.lang.IllegalArgumentException: Root already contains item with identical fullURI = /PlayerManager/Test
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:135)
	at net.sf.rails.game.state.Root.addItem(Root.java:118)
	at net.sf.rails.game.state.Manager.addItem(Manager.java:84)
	at net.sf.rails.game.state.AbstractItem.<init>(AbstractItem.java:33)
	at net.sf.rails.game.RailsAbstractItem.<init>(RailsAbstractItem.java:11)
	at net.sf.rails.game.Player.<init>(Player.java:47)
	at net.sf.rails.game.Player.create(Player.java:98)
	at net.sf.rails.game.PlayerManager.setPlayers(PlayerManager.java:91)
	at net.sf.rails.game.RailsRoot.finishConfiguration(RailsRoot.java:131)
	at net.sf.rails.game.RailsRoot.create(RailsRoot.java:74)
	at net.sf.rails.ui.swing.GameSetupController$NewAction.startNewGame(GameSetupController.java:168)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

Added a fix that checks to make sure all player names are unique before attempting to start the game

**Comment by madoar** [comment]
What happens if the names are not unique? Does it throw an exception (i.e. the one you mentioned) or does a popup open? I'm in favor of a popup that informs the user of the issue so that he can fix it instead of restarting the application.

**Comment by jklap** [comment]
PR #164 is committed, you can eyeball what the change was :)

**Comment by neutronc** [comment]
Is that fixed now @jklap ?

**Comment by jklap** [comment]
Addressed by PR 159
