### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by madoar** [Rails-18xx/Rails#6]
When running `mvn clean test` I still get a failing test:

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building rails 2.0-RC4
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ rails ---
[INFO] Deleting /home/marc/git/Rails/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ rails ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 931 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ rails ---
[INFO] Compiling 470 source files to /home/marc/git/Rails/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ rails ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 56 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ rails ---
[INFO] Compiling 36 source files to /home/marc/git/Rails/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ rails ---
[INFO] Surefire report directory: /home/marc/git/Rails/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running net.sf.rails.test.TestGameBuilder
log4j.configuration =  log4j.properties
Test directory = /home/marc/git/Rails/src/test/resources/data
Added TestGame bugs/1830CF_obsoleteTrains
Added TestGame bugs/1830_sellPresidency
Added TestGame bugs/1835_changePresidentAtStart
Added TestGame bugs/1856_tokens
Added TestGame bugs/1889_presidentContribution
Added TestGame real/1830_A
Added TestGame real/1835_KoIT3
Added TestGame real/1835_Stoll_12
Added TestGame real/1856_A
Added TestGame real/1880_ATG1
Added TestGame real/1889_A
Added TestGame real/1889_B
Added TestGame real/1889_C
Added TestGame real/18AL_A
Added TestGame real/18EU_A
Added TestGame real/18EU_B
Added TestGame test/1830_5forDtrainExchange
Added TestGame test/1830_Auction_Test
Added TestGame test/1830_SellFullPresCert
Added TestGame test/1830_SellHalfPresCert
Added TestGame test/1830_ShareSelling_Test
Added TestGame test/1835_Correct_Sell_Pass
Added TestGame test/1835_NatDoubleShare
Added TestGame test/1835_SellDoubleShare
Added TestGame test/1835_ShareSelling_Test
Added TestGame test/1837_StartRoundCompleted
Added TestGame test/1837_TileLayingCheck-Privates
Added TestGame test/1851_Late
Tests run: 28, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 15.414 sec - in net.sf.rails.test.TestGameBuilder
Running net.sf.rails.test.TestGame
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec <<< FAILURE! - in net.sf.rails.test.TestGame
warning(junit.framework.TestSuite$1)  Time elapsed: 0.002 sec  <<< FAILURE!
junit.framework.AssertionFailedError: Class net.sf.rails.test.TestGame has no public constructor TestCase(String name) or TestCase()
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.TestCase.fail(TestCase.java:227)
	at junit.framework.TestSuite$1.runTest(TestSuite.java:97)

Running net.sf.rails.game.state.ArrayListMultimapStateTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.02 sec - in net.sf.rails.game.state.ArrayListMultimapStateTest
Running net.sf.rails.game.state.ArrayListStateTest
Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.028 sec - in net.sf.rails.game.state.ArrayListStateTest
Running net.sf.rails.game.state.RootTest
Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec - in net.sf.rails.game.state.RootTest
Running net.sf.rails.game.state.ModelTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.123 sec - in net.sf.rails.game.state.ModelTest
Running net.sf.rails.game.state.PortfolioMapTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 sec - in net.sf.rails.game.state.PortfolioMapTest
Running net.sf.rails.game.state.HashMapStateTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 sec - in net.sf.rails.game.state.HashMapStateTest
Running net.sf.rails.game.state.StringStateTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec - in net.sf.rails.game.state.StringStateTest
Running net.sf.rails.game.state.PortfolioSetTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in net.sf.rails.game.state.PortfolioSetTest
Running net.sf.rails.game.state.ManagerTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in net.sf.rails.game.state.ManagerTest
Running net.sf.rails.game.state.HashMultimapStateTest
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 sec - in net.sf.rails.game.state.HashMultimapStateTest
Running net.sf.rails.game.state.ObservableTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.022 sec - in net.sf.rails.game.state.ObservableTest
Running net.sf.rails.game.state.AbstractItemTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in net.sf.rails.game.state.AbstractItemTest
Running net.sf.rails.game.state.PortfolioManagerTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in net.sf.rails.game.state.PortfolioManagerTest
Running net.sf.rails.game.state.ObserverTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in net.sf.rails.game.state.ObserverTest
Running net.sf.rails.game.state.WalletManagerTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in net.sf.rails.game.state.WalletManagerTest
Running net.sf.rails.game.state.BooleanStateTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in net.sf.rails.game.state.BooleanStateTest
Running net.sf.rails.game.state.ChangeStackTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in net.sf.rails.game.state.ChangeStackTest
Running net.sf.rails.game.state.IntegerStateTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec - in net.sf.rails.game.state.IntegerStateTest
Running net.sf.rails.game.state.GenericStateTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in net.sf.rails.game.state.GenericStateTest
Running net.sf.rails.game.state.HashSetStateTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 sec - in net.sf.rails.game.state.HashSetStateTest
Running net.sf.rails.game.state.StateManagerTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.046 sec - in net.sf.rails.game.state.StateManagerTest
Running net.sf.rails.game.state.StateTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in net.sf.rails.game.state.StateTest
Running net.sf.rails.game.state.WalletBagTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in net.sf.rails.game.state.WalletBagTest

Results :

Failed tests: 
  TestSuite$1.warning Class net.sf.rails.test.TestGame has no public constructor TestCase(String name) or TestCase()

Tests run: 170, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 26.148 s
[INFO] Finished at: 2017-07-10T15:23:02+02:00
[INFO] Final Memory: 31M/350M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project rails: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/marc/git/Rails/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

I'm not sure how to fix this, @neutronc can you take a look at this?

**Comment by neutronc** [comment]
TestGame is itself no test but used to do tests. It shouldnt be tested itself but only be used as a test.
I dont known maven so i cant help you there. Perhaps someone else can ?

**Comment by madoar** [comment]
Ok, I've found a solution.
To prevent JUnit from using `TestGame` as a test class we need to annotate it with `@Ignore`.
As far as I understand junit this will prevent junit from viewing `TestGame` as a standalone class.

**Comment by madoar** [comment]
This has been fixed by #7. I'm not sure, but I think we should take a look at the way the tests are written and maybe change them a little bit, so that they are more maven conform.

**Comment by neutronc** [comment]
Guten Abend,

waere folgender Ansatz mit den excludes nicht einfacher ?
http://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html

Gruss
Martin

Am 10.07.17 um 15:47 schrieb madoar:

**Comment by madoar** [comment]
That would be a possible alternative too.
I'll change the pom file to use a test exclusion.

**Comment by madoar** [comment]
Test exclusion works and is now pushed to #7.
